log_level: debug
recompress_content: false

file_mappings:
  myfile.m3u:
    backend_url: "https://raw.githubusercontent.com/Loordubmary/how-to-make-m3u-playlist/refs/heads/master/sample-playlist.m3u"
    regex_patterns:
      "commondatastorage": "mysubdomain"
  anotherfile.m3u:
    backend_url: "https://raw.githubusercontent.com/Loordubmary/how-to-make-m3u-playlist/refs/heads/master/sample-playlist.m3u"
    regex_patterns:
      "http://commondatastorage.googleapis.com": "http://127.0.0.1:8000"
